name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Publish PyPI package
        uses: cadifyai/poetry-publish@v0.1.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REGISTRY_USER: ${{ secrets.PYPI_EXOGROUP_USER }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_EXOGROUP_SECRET }}
          PUBLISH_REGISTRY: ${{ vars.PYPI_EXOGROUP_URL }}
